import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/shared/components/Navbar";
import { poppins } from "@/shared/fonts";
import Footer from "@/shared/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`h-full antialiased ${poppins.className}`}>
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
